CREATE TABLE ROLES
(
  ROLE_ID INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_35F577BE_37FC_4CC5_8D18_6ECB4955C493) AUTO_INCREMENT NOT NULL,
  ROLE_NAME VARCHAR(250) NOT NULL,
  CONSTRAINT ROLES_USER_ROLES_ROLE_ID_FK FOREIGN KEY (ROLE_ID) REFERENCES USER_ROLES (ROLE_ID)
);
CREATE UNIQUE INDEX "roles_role_name_uindex" ON ROLES (ROLE_NAME);
CREATE TABLE USERS
(
  USER_ID INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_012092B0_8072_4385_A00A_25E0F26E2680) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  USER_NAME VARCHAR(250) NOT NULL,
  PASSWORD VARCHAR(250) NOT NULL,
  CONSTRAINT USERS_USER_ROLES_USER_ROLE_ID_FK FOREIGN KEY (USER_ID) REFERENCES USER_ROLES (USER_ID) ON DELETE CASCADE
);
CREATE TABLE USER_ROLES
(
  USER_ROLE_ID INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_438F8491_6F62_4115_B861_915457072594) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  USER_ID INTEGER NOT NULL,
  ROLE_ID INTEGER NOT NULL
);
CREATE UNIQUE INDEX USERS_USER_ROLES_USER_ROLE_ID_FK_INDEX_C ON USER_ROLES (USER_ID);
CREATE UNIQUE INDEX ROLES_USER_ROLES_ROLE_ID_FK_INDEX_C ON USER_ROLES (ROLE_ID);